homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  customize_domain:
    script:
      custom_ui_state_card: state-card-script-custom-text

tts:
  - platform: google

alarm_control_panel:
  - platform: manual
    pending_time: 5

cover: !include covers.yaml

config:

updater:

discovery:

conversation:

logbook:

map:

sun:

cloud:
  
notify:

python_script:

camera: !include camera.yaml

ios: !include ios.yaml

weather: !include weather.yaml

frontend: !include frontend.yaml

http: !include http.yaml

history: !include history.yaml

panel_iframe: !include panel_iframe.yaml

input_number: !include input_number.yaml

input_text: !include input_text.yaml

switch: !include switches.yaml

weblink: !include weblinks.yaml

device_tracker: !include device_tracker.yaml

media_player: !include media_player.yaml

binary_sensor: !include binary_sensors.yaml

climate: !include climate.yaml

google_assistant: !include googleassistant.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

light: !include lights.yaml

sensor: !include sensors.yaml

mqtt: !include mqtt.yaml

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

recorder: !include recorder.yaml
