homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  customize_domain:
    script:
      custom_ui_state_card: state-card-script-custom-text

customizer:
  custom_ui: local

tts:
  - platform: google

alarm_control_panel:
  - platform: manual
    pending_time: 5

cover:
  - platform: mqtt
    name: "Living Room Covers"
    command_topic: "home-assistant/cover/set"
    state_topic: "home-assistant/cover/state"
    availability_topic: "home-assistant/cover/availability"
    qos: 0
    retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    state_open: "open"
    state_closed: "closed"
    payload_available: "online"
    payload_not_available: "offline"
    optimistic: false
    value_template: '{{ value.x }}'
    tilt_command_topic: 'home-assistant/cover/tilt'
    tilt_status_topic: 'home-assistant/cover/tilt-state'
    tilt_min: 0
    tilt_max: 180
    tilt_closed_value: 70
    tilt_opened_value: 180

config:

updater:

discovery:

conversation:

logbook:

map:

sun:

cloud:
  
notify:

python_script:

ios: !include ios.yaml

weather: !include weather.yaml

frontend: !include frontend.yaml

http: !include http.yaml

history: !include history.yaml

panel_iframe: !include panel_iframe.yaml

input_number: !include input_number.yaml
  
variable: !include variables.yaml

switch: !include switches.yaml

weblink: !include weblinks.yaml

device_tracker: !include device_tracker.yaml

media_player: !include media_player.yaml

binary_sensor: !include binary_sensors.yaml

climate: !include climate.yaml

google_assistant: !include googleassistant.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

light: !include lights.yaml

sensor: !include sensors.yaml

mqtt: !include mqtt.yaml

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

recorder: !include recorder.yaml
